# Generated by Django 5.0.6 on 2024-06-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=30)),
                ('useremail', models.EmailField(max_length=254)),
                ('userdob', models.DateField()),
                ('usergender', models.CharField(max_length=6)),
                ('usercity', models.CharField(max_length=100)),
                ('usercountry', models.CharField(max_length=180)),
                ('useraddress', models.CharField(max_length=400)),
                ('userabout', models.TextField()),
                ('userserial', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
