# Generated by Django 5.0.6 on 2024-06-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ADD_CATEGORY', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=250)),
                ('taskDescription', models.TextField()),
                ('is_Completed', models.BooleanField(default=False)),
                ('taskAssignDate', models.DateTimeField(auto_now=True)),
                ('taskCategory', models.ManyToManyField(to='ADD_CATEGORY.categorymodel')),
            ],
        ),
    ]
