# Generated by Django 5.0.6 on 2024-06-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='nameSlug',
            field=models.SlugField(blank=True, max_length=400, null=True, unique=True),
        ),
    ]
