# Generated by Django 5.0.6 on 2024-06-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicianModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=250)),
                ('user_last_name', models.CharField(max_length=250)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone_number', models.CharField(max_length=12)),
                ('user_instrument', models.CharField(max_length=500)),
            ],
        ),
    ]
