# Generated by Django 5.0.6 on 2024-06-16 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0002_musicianmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicianmodel',
            name='author',
        ),
    ]
