# Generated by Django 5.0.6 on 2024-06-16 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_remove_albummodel_musician'),
        ('musician', '0003_remove_musicianmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicianmodel',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.albummodel'),
        ),
    ]
