# Generated by Django 5.0.6 on 2024-06-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_albummodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albummodel',
            name='author',
        ),
    ]
