# Generated by Django 5.0.6 on 2024-06-16 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_remove_albummodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albummodel',
            name='musician',
        ),
    ]
