# Generated by Django 5.0.6 on 2024-06-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postmodel_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='post_author',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='post_category',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='posts/media/uploads/'),
        ),
    ]
