# Generated by Django 5.0.6 on 2024-06-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('posts', '0004_postmodel_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='post_category',
            field=models.ManyToManyField(blank=True, null=True, to='category.categorymodel'),
        ),
    ]
