# Generated by Django 5.0.6 on 2024-06-13 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postmodel_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author_username', models.CharField(max_length=25)),
                ('comment_author_email', models.EmailField(max_length=254)),
                ('comment_create_time', models.DateTimeField(auto_now_add=True)),
                ('comment_body', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.postmodel')),
            ],
        ),
    ]
