# Generated by Django 5.0.6 on 2024-06-18 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=60)),
                ('comment', models.TextField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('car_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmnt', to='carinfo.cardetailmodel')),
            ],
        ),
    ]
