# Generated by Django 5.0.6 on 2024-06-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='comment',
            new_name='comment_body',
        ),
    ]
