# Generated by Django 5.0.6 on 2024-06-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='bio',
            field=models.TextField(default='Null'),
        ),
    ]
