# Generated by Django 5.0.6 on 2024-06-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('first_Name', models.CharField(max_length=15)),
                ('last_Name', models.CharField(max_length=15)),
                ('user_Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('user_Password', models.CharField(max_length=20)),
            ],
        ),
    ]
