# Generated by Django 5.0.6 on 2024-06-01 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_users_id_users_userid_alter_users_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='userId',
        ),
    ]
