# Generated by Django 5.0.6 on 2024-06-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_users_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='user_Email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
