# Generated by Django 5.0.6 on 2024-06-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_userbankaccount_user_useraddressmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddressmodel',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='userregistrationmodel',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='userregistrationmodel',
            name='deposite_date',
        ),
        migrations.AddField(
            model_name='useraddressmodel',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userregistrationmodel',
            name='account_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userregistrationmodel',
            name='initial_deposite_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Current', 'Current'), ('Savigs', 'Savings')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
