# Generated by Django 5.0.6 on 2024-06-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_useraddressmodel_post_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistrationmodel',
            name='initial_deposite_date',
        ),
        migrations.AddField(
            model_name='userregistrationmodel',
            name='deposite_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='city',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='country',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='street_address',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Current', 'Current'), ('Savigs', 'Savings')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
    ]
