# Generated by Django 5.0.6 on 2024-06-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_userregistrationmodel_initial_deposite_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddressmodel',
            old_name='postal_code',
            new_name='post_code',
        ),
        migrations.RenameField(
            model_name='userregistrationmodel',
            old_name='account_no',
            new_name='account_number',
        ),
    ]
