# Generated by Django 5.0.6 on 2024-06-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('schedule', models.DateTimeField()),
                ('duartion', models.DurationField()),
                ('cgpa', models.DecimalField(decimal_places=5, max_digits=5)),
                ('careerpath', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('balance', models.BigIntegerField()),
            ],
        ),
    ]
