# Generated by Django 5.0.6 on 2024-06-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0002_authormodel_bio'),
        ('Posts', '0002_remove_postsmodel_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorModel',
        ),
    ]
