# Generated by Django 5.0.6 on 2024-06-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='albumreleasedate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
