# Generated by Django 5.0.6 on 2024-05-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
