const mobileInfos = [
  {
    id: 1,
    brand: "Apple",
    deviceModel: "iPhone 12",
    color: "Black",
    price: 999,
    madeIn: "USA",
  },
  {
    id: 2,
    brand: "Samsung",
    deviceModel: "Galaxy S21",
    color: "Black",
    price: 1099,
    madeIn: "South Korea",
  },
  {
    id: 3,
    brand: "Google",
    deviceModel: "Pixel 5",
    color: "White",
    price: 799,
    madeIn: "USA",
  },
  {
    id: 4,
    brand: "Sony",
    deviceModel: "Xperia 1 III",
    color: "White",
    price: 1299,
    madeIn: "Japan",
  },
  {
    id: 5,
    brand: "Microsoft",
    deviceModel: "Surface Laptop 4",
    color: "Blue",
    price: 1299,
    madeIn: "USA",
  },
  {
    id: 6,
    brand: "Apple",
    deviceModel: "iPad Pro",
    color: "Blue",
    price: 799,
    madeIn: "China",
  },
  {
    id: 7,
    brand: "Samsung",
    deviceModel: "Galaxy Watch 4",
    color: "White",
    price: 349,
    madeIn: "Vietnam",
  },
  {
    id: 8,
    brand: "Google",
    deviceModel: "Nest Audio",
    color: "Black",
    price: 99,
    madeIn: "China",
  },
  {
    id: 9,
    brand: "Sony",
    deviceModel: "PlayStation 5",
    color: "Black",
    price: 499,
    madeIn: "China",
  },
  {
    id: 10,
    brand: "Microsoft",
    deviceModel: "Xbox Series X",
    color: "Black",
    price: 499,
    madeIn: "China",
  },
  {
    id: 11,
    brand: "Apple",
    deviceModel: "iPhone 11",
    color: "White",
    price: 699,
    madeIn: "USA",
  },
  {
    id: 12,
    brand: "Samsung",
    deviceModel: "Galaxy Note 20",
    color: "Blue",
    price: 999,
    madeIn: "South Korea",
  },
  {
    id: 13,
    brand: "Google",
    deviceModel: "Pixel 4a",
    color: "Blue",
    price: 349,
    madeIn: "USA",
  },
  {
    id: 14,
    brand: "Sony",
    deviceModel: "Xperia 5 II",
    color: "Black",
    price: 899,
    madeIn: "Japan",
  },
  {
    id: 15,
    brand: "Microsoft",
    deviceModel: "Surface Pro 7",
    color: "White",
    price: 899,
    madeIn: "USA",
  },
];

const blackmobiles = mobileInfos.filter(
  (mobile) => mobile.color.toLowerCase() == "black"
);

console.log(...blackmobiles);
