# Generated by Django 5.0.6 on 2024-06-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('studentName', models.CharField(max_length=50)),
                ('fatherName', models.CharField(max_length=50)),
                ('motherName', models.CharField(max_length=50)),
                ('studentAddress', models.TextField()),
                ('studentAge', models.IntegerField()),
                ('serialId', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
