CREATE DATABASE SCHOOL;
USE SCHOOL;
CREATE TABLE STUDENT (
    S_NAME VARCHAR(50) NOT NULL,
    S_ROLL INT,
    S_ID CHAR(11) PRIMARY KEY,
    S_CLASS INT NOT NULL,
    S_EMAIL VARCHAR(50),
    CONSTRAINT ROLL_REQ UNIQUE (S_ROLL),
    CONSTRAINT EMAIL_REQ UNIQUE (S_EMAIL)
);
CREATE TABLE LIBRARY (
    BOOK_NAME VARCHAR(50) NOT NULL,
    DAYSHOLD INT NOT NULL,
    ID CHAR(11),
    FOREIGN KEY (ID)
        REFERENCES STUDENT (S_ID),
    CONSTRAINT ID_REQ PRIMARY KEY (ID)
);
CREATE TABLE FEES (
    STUDENT_ID CHAR(11),
    EXTRA_DAYS INT,
    FINE INT,
    FOREIGN KEY (STUDENT_ID)
        REFERENCES STUDENT (S_ID),
    CONSTRAINT ID_REQ PRIMARY KEY (STUDENT_ID)
);
use school;
drop database school;