# Generated by Django 5.0.6 on 2024-06-03 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicianModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('useremail', models.EmailField(max_length=254)),
                ('userphone', models.CharField(max_length=12)),
                ('intrumenttype', models.CharField(max_length=150)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Album.albummodel')),
            ],
        ),
    ]
