# Generated by Django 5.0.6 on 2024-06-18 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carbrand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=350)),
                ('car_title', models.CharField(max_length=450)),
                ('car_description', models.TextField()),
                ('car_quantity', models.IntegerField()),
                ('car_price', models.IntegerField()),
                ('car_image', models.ImageField(upload_to='carinfo/media/upload')),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbrand.carbrandmodel')),
            ],
        ),
    ]
