# Generated by Django 5.0.6 on 2024-06-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userAddress',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='users',
            name='userEmail',
            field=models.EmailField(max_length=150),
        ),
    ]
