# Generated by Django 5.0.6 on 2024-06-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_users_useraddress_alter_users_useremail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='usersID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
