# Generated by Django 5.0.6 on 2024-06-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_users_id_alter_users_usersid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='usersID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
