from django.shortcuts import render

# Create your views here.
users_data = {
    "users": [
        {
            "username": "jdoe",
            "useremail": "jdoe@example.com",
            "userjob_title": "Software Engineer",
            "useraddress": "123 Elm St, Springfield, IL 62701",
            "usersalary": "$95,000",
            "userphone": "217-555-1234",
            "userdescription": "A passionate software engineer with 5 years of experience in full-stack development.",
            "usergender": "Male",
            "usereducational_background": "B.Sc. in Computer Science from University of Illinois",
            "relation_status": False,
            "portfolioLink": "http://jdoe-portfolio.com",
            "full_name": "John Doe",
            "age": 30,
            "job_history": [
                {
                    "company_name": "TechCorp",
                    "job_title": "Junior Developer",
                    "salary": "$60,000",
                    "days_worked": 730,
                },
                {
                    "company_name": "Innovatech",
                    "job_title": "Software Engineer",
                    "salary": "$80,000",
                    "days_worked": 1095,
                },
                {
                    "company_name": "DevSolutions",
                    "job_title": "Senior Developer",
                    "salary": "$90,000",
                    "days_worked": 730,
                },
                {
                    "company_name": "CodeMasters",
                    "job_title": "Lead Developer",
                    "salary": "$100,000",
                    "days_worked": 365,
                },
            ],
        },
        {
            "username": "asmith",
            "useremail": "asmith@example.com",
            "userjob_title": "Marketing Manager",
            "useraddress": "456 Oak St, Chicago, IL 60601",
            "usersalary": "$85,000",
            "userphone": "312-555-5678",
            "userdescription": "Experienced marketing manager with a strong background in digital marketing strategies.",
            "usergender": "Female",
            "usereducational_background": "M.B.A. in Marketing from Northwestern University",
            "relation_status": True,
            "portfolioLink": "http://asmith-portfolio.com",
            "full_name": "Anna Smith",
            "age": 35,
            "job_history": [
                {
                    "company_name": "MarketMinds",
                    "job_title": "Marketing Assistant",
                    "salary": "$50,000",
                    "days_worked": 365,
                },
                {
                    "company_name": "AdvertisePro",
                    "job_title": "Senior Marketing Specialist",
                    "salary": "$70,000",
                    "days_worked": 730,
                },
                {
                    "company_name": "BrandBuilders",
                    "job_title": "Marketing Lead",
                    "salary": "$75,000",
                    "days_worked": 365,
                },
                {
                    "company_name": "PromoGurus",
                    "job_title": "Marketing Manager",
                    "salary": "$80,000",
                    "days_worked": 730,
                },
            ],
        },
        {
            "username": "bwilliams",
            "useremail": "bwilliams@example.com",
            "userjob_title": "Data Scientist",
            "useraddress": "789 Pine St, San Francisco, CA 94101",
            "usersalary": "$120,000",
            "userphone": "415-555-8765",
            "userdescription": "Data scientist with expertise in machine learning and big data analytics.",
            "usergender": "Male",
            "usereducational_background": "Ph.D. in Statistics from Stanford University",
            "relation_status": False,
            "portfolioLink": "http://bwilliams-portfolio.com",
            "full_name": "Brian Williams",
            "age": 40,
            "job_history": [
                {
                    "company_name": "DataWorld",
                    "job_title": "Data Analyst",
                    "salary": "$65,000",
                    "days_worked": 365,
                },
                {
                    "company_name": "InsightAnalytics",
                    "job_title": "Senior Data Scientist",
                    "salary": "$110,000",
                    "days_worked": 1095,
                },
                {
                    "company_name": "BigDataSolutions",
                    "job_title": "Lead Data Scientist",
                    "salary": "$115,000",
                    "days_worked": 730,
                },
                {
                    "company_name": "AI Innovators",
                    "job_title": "Chief Data Scientist",
                    "salary": "$125,000",
                    "days_worked": 365,
                },
            ],
        },
        {
            "username": "cliu",
            "useremail": "cliu@example.com",
            "userjob_title": "Graphic Designer",
            "useraddress": "321 Maple St, New York, NY 10001",
            "usersalary": "$70,000",
            "userphone": "212-555-4321",
            "userdescription": "Creative graphic designer with a passion for visual storytelling and branding.",
            "usergender": "Female",
            "usereducational_background": "B.A. in Graphic Design from Rhode Island School of Design",
            "relation_status": True,
            "portfolioLink": "http://cliu-portfolio.com",
            "full_name": "Catherine Liu",
            "age": 28,
            "job_history": [
                {
                    "company_name": "DesignWorks",
                    "job_title": "Junior Designer",
                    "salary": "$45,000",
                    "days_worked": 730,
                },
                {
                    "company_name": "CreativeAgency",
                    "job_title": "Lead Graphic Designer",
                    "salary": "$65,000",
                    "days_worked": 1095,
                },
                {
                    "company_name": "ArtistryStudio",
                    "job_title": "Art Director",
                    "salary": "$75,000",
                    "days_worked": 730,
                },
                {
                    "company_name": "VisualFX",
                    "job_title": "Senior Art Director",
                    "salary": "$85,000",
                    "days_worked": 365,
                },
            ],
        },
        {
            "username": "djohnson",
            "useremail": "djohnson@example.com",
            "userjob_title": "Project Manager",
            "useraddress": "654 Cedar St, Seattle, WA 98101",
            "usersalary": "$110,000",
            "userphone": "206-555-7890",
            "userdescription": "Project manager with a track record of successfully leading cross-functional teams.",
            "usergender": "Non-binary",
            "usereducational_background": "M.S. in Project Management from University of Washington",
            "relation_status": True,
            "portfolioLink": "http://djohnson-portfolio.com",
            "full_name": "Dana Johnson",
            "age": 38,
            "job_history": [
                {
                    "company_name": "BuildIt",
                    "job_title": "Project Coordinator",
                    "salary": "$60,000",
                    "days_worked": 730,
                },
                {
                    "company_name": "TechSolutions",
                    "job_title": "Project Manager",
                    "salary": "$95,000",
                    "days_worked": 1095,
                },
                {
                    "company_name": "InnovateManage",
                    "job_title": "Senior Project Manager",
                    "salary": "$100,000",
                    "days_worked": 730,
                },
                {
                    "company_name": "GlobalProjects",
                    "job_title": "Director of Projects",
                    "salary": "$120,000",
                    "days_worked": 365,
                },
            ],
        },
        {
            "username": "emartinez",
            "useremail": "emartinez@example.com",
            "userjob_title": "HR Specialist",
            "useraddress": "987 Birch St, Austin, TX 73301",
            "usersalary": "$75,000",
            "userphone": "512-555-6543",
            "userdescription": "HR specialist focused on employee engagement and organizational development.",
            "usergender": "Female",
            "usereducational_background": "B.A. in Human Resources from University of Texas at Austin",
            "relation_status": False,
            "portfolioLink": "http://emartinez-portfolio.com",
            "full_name": "Elena Martinez",
            "age": 32,
            "job_history": [
                {
                    "company_name": "PeopleFirst",
                    "job_title": "HR Assistant",
                    "salary": "$45,000",
                    "days_worked": 365,
                },
                {
                    "company_name": "HRPros",
                    "job_title": "HR Specialist",
                    "salary": "$65,000",
                    "days_worked": 730,
                },
                {
                    "company_name": "TalentBoost",
                    "job_title": "Senior HR Specialist",
                    "salary": "$70,000",
                    "days_worked": 730,
                },
                {
                    "company_name": "EmployeeEngage",
                    "job_title": "HR Manager",
                    "salary": "$80,000",
                    "days_worked": 365,
                },
            ],
        },
    ]
}


def productsHome(req):
    return render(req, "Products/index.html", users_data)
    